// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cZIF1MTroqPU-V6ShTlCpRv7WexNvns',
    appId: '1:716434862825:web:b9d302680d1204f8a97678',
    messagingSenderId: '716434862825',
    projectId: 'mysaloon-a4891',
    authDomain: 'mysaloon-a4891.firebaseapp.com',
    storageBucket: 'mysaloon-a4891.firebasestorage.app',
    measurementId: 'G-ZNR113VVGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqNjKaw_d9GP76qk_Crp7Rnc0LqD7i4SM',
    appId: '1:716434862825:android:b41e00cd86d40205a97678',
    messagingSenderId: '716434862825',
    projectId: 'mysaloon-a4891',
    storageBucket: 'mysaloon-a4891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAajlOlk3DsMomO9R6qX-dzVxDkQqKCPvU',
    appId: '1:716434862825:ios:cb3a2ec1737e2c0da97678',
    messagingSenderId: '716434862825',
    projectId: 'mysaloon-a4891',
    storageBucket: 'mysaloon-a4891.firebasestorage.app',
    iosBundleId: 'com.example.salonBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAajlOlk3DsMomO9R6qX-dzVxDkQqKCPvU',
    appId: '1:716434862825:ios:cb3a2ec1737e2c0da97678',
    messagingSenderId: '716434862825',
    projectId: 'mysaloon-a4891',
    storageBucket: 'mysaloon-a4891.firebasestorage.app',
    iosBundleId: 'com.example.salonBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0cZIF1MTroqPU-V6ShTlCpRv7WexNvns',
    appId: '1:716434862825:web:816a5080d3f9eda5a97678',
    messagingSenderId: '716434862825',
    projectId: 'mysaloon-a4891',
    authDomain: 'mysaloon-a4891.firebaseapp.com',
    storageBucket: 'mysaloon-a4891.firebasestorage.app',
    measurementId: 'G-J3M6EDDPJF',
  );
}
